package de.godcipher.config.annotation;

import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;

@Retention(RetentionPolicy.RUNTIME)
@Target(ElementType.TYPE)
public @interface Configuration {
  /**
   * Specifies the fully qualified name of the configuration file.
   *
   * <p>This represents the file name, including the extension.
   *
   * <p>Example usage:
   *
   * <pre>
   *     {@code fileName = "config.yml"}
   * </pre>
   */
  String fileName();

  /**
   * Specifies the header lines for the configuration file.
   *
   * <p>Each line in the array will be prefixed with a {@code #} symbol, indicating a comment in the
   * configuration file.
   *
   * <p>Example usage:
   *
   * <pre>
   *     {@code header = {"Configuration File", "Generated by gutil"}}
   * </pre>
   *
   * <p>This will generate the following output in the configuration file:
   *
   * <pre>
   *     # Configuration File
   *     # Generated by gutil
   * </pre>
   *
   * <p>If no header is specified, the default header will be:
   *
   * <pre>
   *     # Configuration File
   *     # Generated by gutil
   * </pre>
   */
  String[] header() default {"Configuration File", "Generated by gutil"};
}
