package de.godcipher.gutil.config.annotation;

import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;

@Retention(RetentionPolicy.RUNTIME)
@Target(ElementType.TYPE)
public @interface ConfigHeader {
  /**
   * Defines the lines of the header to be included in the configuration file. Each line will be
   * treated as a comment in the configuration file.
   *
   * <p>Example:
   *
   * <pre>
   * {@code value = {"Configuration File", "Generated by gutil"}}
   * </pre>
   *
   * Will result in:
   *
   * <pre>
   * # Configuration File
   * # Generated by gutil
   * </pre>
   *
   */
  String[] value() default {"Configuration File", "Generated by gutil"};
}
